server {
    listen 80;
    server_name compared.work www.compared.work;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name compared.work www.compared.work;

    ssl_certificate /etc/ssl/certs/compared.work.pem;
    ssl_certificate_key /etc/ssl/private/compared.work.key;

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/compare.django/gunicorn.sock;
    }

    location /static/ {
        alias /var/www/compare.django/staticfiles/;
    }
}
