name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-render:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  deploy-droplet:
    name: Deploy to Droplet
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.GITHUBACTIONSDEPLOY147_182_211_216 }}
          script: bash /var/www/compare.django/deploy.sh
